# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_de', models.CharField(max_length=45)),
                ('part_describe_de', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=45)),
                ('download', models.CharField(max_length=45)),
            ],
        ),
    ]
