# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0002_auto_20170114_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='download',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='img',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='part_cn',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='part_de',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='part_describe_cn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='part_describe_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='part_describe_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='part_en',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
