# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0003_auto_20170114_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cover', models.CharField(max_length=45, null=True)),
                ('book_download', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
