# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0004_edu'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='book_price',
            field=models.IntegerField(default=0),
        ),
    ]
