# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0006_calender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calender',
            new_name='Calendar',
        ),
    ]
