# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0007_auto_20170115_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='schedule',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
