# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0008_auto_20170115_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='daytime',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
