# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0009_auto_20170115_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
