# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0010_calendar_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='color',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
