# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0011_calendar_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=45, null=True)),
                ('support', models.CharField(max_length=200, null=True)),
                ('projectDescribe', models.CharField(max_length=200, null=True)),
                ('discussionLink', models.CharField(max_length=200, null=True)),
                ('detailLink', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
