# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0014_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='detailLink',
        ),
        migrations.DeleteModel(
            name='ProjectDetail',
        ),
        migrations.AddField(
            model_name='course',
            name='uni_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosmis_zh_cn.University'),
        ),
    ]
