# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0015_auto_20170116_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
