# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0016_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(default='', max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_question', models.CharField(default='', max_length=450)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosmis_zh_cn.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment_reply',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosmis_zh_cn.Comments'),
        ),
        migrations.AddField(
            model_name='comment_reply',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosmis_zh_cn.User'),
        ),
    ]
