# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0017_auto_20170206_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_text',
            field=models.CharField(default='', max_length=450),
        ),
    ]
