# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0018_comments_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_text',
        ),
    ]
