# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0022_comments_replies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_reply',
            old_name='comment_id',
            new_name='comment_question',
        ),
    ]
