# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0023_auto_20170209_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_url', models.CharField(max_length=45, null=True)),
                ('explain_url', models.CharField(max_length=45, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosmis_zh_cn.Project')),
            ],
        ),
    ]
