# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0025_project_detail_download_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_detail',
            name='download_url',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='explain_url',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='project_detail',
            name='show_url',
            field=models.CharField(default='', max_length=45),
        ),
    ]
