# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0027_auto_20170209_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='movie',
            field=models.CharField(default='', max_length=45, null=True),
        ),
    ]
