# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0028_learn_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='part_describe_de',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
