# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosmis_zh_cn', '0029_auto_20170320_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='book_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
